'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

    return queryInterface.bulkInsert('Exercises', [{
      //  =========================================== LOWER BODY ==========================================
      name: "Barbell Squat",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Box Jumps",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dead Lift",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Walking Lunges",
      muscle_group: "quads",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Calf Raises",
      muscle_group: "calves",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded Squat Pulses",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Lying Hamstring Curls",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Physioball Hamstring Curls",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dumbbell Hamstring Curl",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded Hip Abductors",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Leg Extensions",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Lower Back Extension",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded Squats",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded Leg Press",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Sumo Squats",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Single Leg RDLs ",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Romanian Dead Lifts",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cable Kickbacks",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Bulgarian Split Squats",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Reverse Lunges",
      muscle_group: "quads",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Hack Squats",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cable Pull-Throughs",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Good Mornings",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Curtsy Lunges",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Barbell Glute Bridges",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded BW Glute Bridges",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Front Squats",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Goblet Squats",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Wall Sit",
      muscle_group: "gltues",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cable Front Squat",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Duck Walks",
      muscle_group: "hamstrings",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Sissy Squats",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded Sidesteps",
      muscle_group: "glutes",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Step Ups",
      muscle_group: "quads",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Sliding Lunges",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Leg Press",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Close Stance Smith Squats ",
      muscle_group: "quads",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Weighted Box Squat",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Single Leg Box Squat",
      muscle_group: "quads",
      type: "lower",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Single Leg Squat off Box",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Trap Bar Dead Lift",
      muscle_group: "glutes",
      type: "lower",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    //  =========================================== UPPER BODY ==========================================
    {
      name: "Shoulder Press",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dumbbell Row",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cable Row",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Wide Grip Lat Pull Down",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Close Grip Lat Pull Down",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Underhand Lat Pull Down",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Pushups",
      muscle_group: "chest",
      type: "upper",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dumbbell Pullover",
      muscle_group: "chest",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Pull Ups",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Lat Pushdown",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Crossed Cable Pulldown",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Back Extension",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Bench Press",
      muscle_group: "chest",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dumbell Chest Press",
      muscle_group: "chest",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Pec Deck Flys",
      muscle_group: "chest",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Reverse Pec Deck",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Rear Delt Raises",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Plate Press",
      muscle_group: "chest",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Landmine Press",
      muscle_group: "chest",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Face Pulls",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Medball Front x Overhead Press",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Tricep Extensions",
      muscle_group: "triceps",
      type: "upper",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Plate Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Lateral Raises",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Banded Lateral Hold",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Front Raises",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Seated Dumbbell Shoudler Press",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cable Front Raise Superset",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cable Tricep Pushdowns",
      muscle_group: "triceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    {
      name: "Single Arm Cable Curls (Face-Away)",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Single Arm Cable Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Rope Hammer Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dumbbell Hammer Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Drag Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Crazy Eights: Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Barbell Row",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Tricep Dips",
      muscle_group: "triceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Upright Row to Press",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Upright Row",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Skull Crushers",
      muscle_group: "triceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Single Underhand Tricep Extension",
      muscle_group: "triceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dumbbell Bicep Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Overhand Barbell Curls",
      muscle_group: "biceps",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Arnold Press",
      muscle_group: "shoulders",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Chinups",
      muscle_group: "back",
      type: "upper",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Wide Grip Lat Pull Down",
      muscle_group: "back",
      type: "upper",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    //  =========================================== CARDIO ==========================================
    {
      name: "Jumprope",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Duck Unders",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Jumping Jacks",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Kettle Bell Swings",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Jumping Lunges",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Squat Jumps",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Toe Taps",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Sprints",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Burpees",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Mountain Climbers",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Box Jumps",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Box Ski Jumps",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Interval Runs",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Kneel to Squat",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "High Knees",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Eliptical",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Row Machine",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Exercise Bike",
      type: "cardio",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    //  =========================================== CORE ==========================================
    {
      name: "Leg Lifts",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Flutter Kicks",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "V-Ups",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Jacknives",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Medball Pass",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Medball Sit Ups",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Plank",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Hollow Hold",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Rollouts",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Russian Twists",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Wood Choppers",
      muscle_group: "core",
      type: "core",
      aerobic: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Hanging Leg Raises",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dead Bugs",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Plank Knee to Chest",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Physioball Pass",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Physioball Sit Ups",
      muscle_group: "core",
      type: "core",
      aerobic: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  }
};
